import { numberToUUID } from "@capacitor-community/bluetooth-le";

const BLE_CORE_SERVICE_UUID = numberToUUID(0x180f);
const BLE_BMS_STATE_UUID = "549fa451-cf65-4ea1-a462-9527d8d06440";
const BLE_PSU_STATE_UUID = "bd9e30e5-3e45-4660-8a1f-2a4f12bfaa5e";
const BLE_MCU_STATE_UUID = "a61dc670-fb5c-4f8c-afa8-7bcd088dc146";
const BLE_INVERTER_STATE_UUID = "226396fe-22a8-48ce-aa95-188899618fd9";
const BLE_ATS_STATE_UUID = "c56dc4f9-9b70-4c42-8044-e62f7e4a8894";

const BLE_LOG_STATE_UUID = "ab933689-588b-4b99-9f79-50a6f26415ae";

const BLE_OTA_STATE_UUID = "ee0391bd-5d94-4593-ab06-91078aa48cc9";

const BLE_HISTORY_STATE_UUID = "b1e71c63-5154-4bc5-bad6-4dc170b926d4";
const BLE_RUN_COMMAND_UUID = "eb47891b-c111-463b-8f39-4a5115c352bd";

const COMMAND_PULL_HISTORY = 0x01;
const COMMAND_PSU_ENABLE = 0x10;
const COMMAND_PSU_DISABLE = 0x11;
const COMMAND_PSU_TURBO = 0x12;

const COMMAND_INVERTER_ENABLE = 0x20;
const COMMAND_INVERTER_DISABLE = 0x21;

const COMMAND_ATS_ENABLE = 0x30;
const COMMAND_ATS_DISABLE = 0x31;

const COMMAND_CONF_SET_KEY = 0x40;
const COMMAND_CONF_PROFILE = 0x41;

const COMMAND_UPDATE_FIRMWARE = 0x50;

const COMMAND_START_LOGS = 0x60;
const COMMAND_STOP_LOGS = 0x61;

const PROFILE_KEY_ATS = 0x00;
const PROFILE_KEY_WIFI_SSID = 0x10;
const PROFILE_KEY_WIFI_PASSWORD = 0x11;
const PROFILE_KEY_PSU_TURBO = 0x20;
const PROFILE_KEY_MIN_VOLTAGE = 0x40;
const PROFILE_KEY_MAX_VOLTAGE = 0x41;

const HISTORY_LENGTH = 180;

const HISTORY_BMS_SOC = 0;
const HISTORY_BMS_CURRENT = 1;
const HISTORY_BMS_CELL1_VOLTAGE = 2;
const HISTORY_BMS_CELL2_VOLTAGE = 3;
const HISTORY_BMS_CELL3_VOLTAGE = 4;
const HISTORY_BMS_CELL4_VOLTAGE = 5;

const HISTORY_PSU_RPM = 10;
const HISTORY_PSU_TEMPERATURE_1 = 11;
const HISTORY_PSU_TEMPERATURE_2 = 12;
const HISTORY_PSU_POWER_1 = 13;
const HISTORY_PSU_POWER_2 = 14;

const HISTORY_INVERTER_POWER = 20;
const HISTORY_INVERTER_TEMPERATURE = 21;
const HISTORY_INVERTER_RPM = 22;

const DATA_TYPE_BYTE = 0;
const DATA_TYPE_WORD = 1;

const POWER_COLOR = "#e89220";
const FAN_COLOR = "#2f6391";
const DC_COLOR = "#9e1b86";
const TEMPERATURE_COLOR = "#60912f";
const CAPACITY_COLOR = "#e89402";

export {
    POWER_COLOR,
    FAN_COLOR,
    DC_COLOR,
    TEMPERATURE_COLOR,
    CAPACITY_COLOR,
    BLE_CORE_SERVICE_UUID,
    BLE_BMS_STATE_UUID,
    BLE_PSU_STATE_UUID,
    BLE_MCU_STATE_UUID,
    BLE_OTA_STATE_UUID,
    BLE_LOG_STATE_UUID,
    BLE_INVERTER_STATE_UUID,
    BLE_ATS_STATE_UUID,
    BLE_HISTORY_STATE_UUID,
    BLE_RUN_COMMAND_UUID,
    HISTORY_LENGTH,
    HISTORY_BMS_SOC,
    HISTORY_BMS_CURRENT,
    HISTORY_BMS_CELL1_VOLTAGE,
    HISTORY_BMS_CELL2_VOLTAGE,
    HISTORY_BMS_CELL3_VOLTAGE,
    HISTORY_BMS_CELL4_VOLTAGE,
    HISTORY_PSU_RPM,
    HISTORY_PSU_TEMPERATURE_1,
    HISTORY_PSU_TEMPERATURE_2,
    HISTORY_PSU_POWER_1,
    HISTORY_PSU_POWER_2,
    HISTORY_INVERTER_POWER,
    HISTORY_INVERTER_TEMPERATURE,
    HISTORY_INVERTER_RPM,
    DATA_TYPE_BYTE,
    DATA_TYPE_WORD,
    COMMAND_PULL_HISTORY,
    COMMAND_PSU_ENABLE,
    COMMAND_PSU_DISABLE,
    COMMAND_PSU_TURBO,
    COMMAND_INVERTER_ENABLE,
    COMMAND_INVERTER_DISABLE,
    COMMAND_ATS_ENABLE,
    COMMAND_ATS_DISABLE,
    COMMAND_CONF_SET_KEY,
    COMMAND_CONF_PROFILE,
    COMMAND_UPDATE_FIRMWARE,
    COMMAND_START_LOGS,
    COMMAND_STOP_LOGS,
    PROFILE_KEY_ATS,
    PROFILE_KEY_WIFI_SSID,
    PROFILE_KEY_WIFI_PASSWORD,
    PROFILE_KEY_PSU_TURBO,
    PROFILE_KEY_MIN_VOLTAGE,
    PROFILE_KEY_MAX_VOLTAGE,
};
